document.addEventListener('DOMContentLoaded', function () {
  const player = new Plyr('#player', {});

  const channelList = document.getElementById('channelList');
  const searchInput = document.getElementById('searchInput');
  const channels = [
{ name: "TVP", url: "https://cdn-nvm-newyork.lolokoko.tv/TVPHD.stream/playlist.m3u8" },
{ name: "TVP 1", url: "https://cdn-nvm-newyork.lolokoko.tv/TVP1.stream/playlist.m3u8" },
{ name: "TVP 2", url: "https://cdn-nvm-newyork.lolokoko.tv/TVP2.stream/playlist.m3u8" },
{ name: "TV Republika", url: "https://cdn-nvm-newyork.lolokoko.tv/TVREPUBLIKA.stream/playlist.m3u8" },
{ name: "w Polsce PL", url: "https://cdn-nvm-newyork.lolokoko.tv/wpolscepl.stream/playlist.m3u8" },
{ name: "Wydarzenia 24", url: "https://cdn-nvm-newyork.lolokoko.tv/superstacja.stream/playlist.m3u8" },
{ name: "Polsat News Polityka", url: "https://cdn-nvm-newyork.lolokoko.tv/polsatnewspolityka.stream/playlist.m3u8" },
{ name: "TVP Info", url: "https://cdn-nvm-newyork.lolokoko.tv/TVPInfo.stream/playlist.m3u8" },
{ name: "WP", url: "https://cdn-nvm-newyork.lolokoko.tv/wp1.stream/playlist.m3u8" },
{ name: "TVN", url: "https://cdn-nvm-newyork.lolokoko.tv/TVN.stream/playlist.m3u8" },
{ name: "TVN 7", url: "https://cdn-nvm-newyork.lolokoko.tv/TVN7.stream/playlist.m3u8" },
{ name: "Polsat", url: "https://cdn-nvm-newyork.lolokoko.tv/Polsat.stream/playlist.m3u8" },
{ name: "Polsat 2", url: "https://cdn-nvm-newyork.lolokoko.tv/Polsat2.stream/playlist.m3u8" },
{ name: "TV 4", url: "https://cdn-nvm-newyork.lolokoko.tv/TV4.stream/playlist.m3u8" },
{ name: "Antena", url: "https://cdn-nvm-newyork.lolokoko.tv/ANTENATV.stream/playlist.m3u8" },
{ name: "Metro", url: "https://cdn-nvm-newyork.lolokoko.tv/METROTV.stream/playlist.m3u8" },
{ name: "Nowa TV", url: "https://cdn-nvm-newyork.lolokoko.tv/NOWATV.stream/playlist.m3u8" },
{ name: "Tele 5", url: "https://cdn-nvm-newyork.lolokoko.tv/Tele5.stream/playlist.m3u8" },
{ name: "HBO", url: "https://cdn-nvm-newyork.lolokoko.tv/HBO.stream/playlist.m3u8" },
{ name: "HBO 2", url: "https://cdn-nvm-newyork.lolokoko.tv/HBO2.stream/playlist.m3u8" },
{ name: "HBO 3"", url: "https://cdn-nvm-newyork.lolokoko.tv/HBO3.stream/playlist.m3u8" },
{ name: "Ale kino+", url: "https://cdn-nvm-newyork.lolokoko.tv/AleKino.stream/playlist.m3u8" },
{ name: "Canal+ Domo", url: "https://cdn-nvm-newyork.lolokoko.tv/domo.stream/playlist.m3u8" },
{ name: "Canal+ Dokument", url: "https://cdn-nvm-newyork.lolokoko.tv/canalplusdokument.stream/playlist.m3u8" },
{ name: "Canal+ Kuchnia", url: "https://cdn-nvm-newyork.lolokoko.tv/kuchniaplus.stream/playlist.m3u8" },
{ name: "Canal+ Family", url: "https://cdn-nvm-newyork.lolokoko.tv/CANALPLUSFAMILY.stream/playlist.m3u8" },
{ name: "Canal+ Seriale", url: "https://cdn-nvm-newyork.lolokoko.tv/CANALPLUSSERIALE.stream/playlist.m3u8" },
{ name: "Canal+ Film", url: "https://cdn-nvm-newyork.lolokoko.tv/CANALPLUSFILM.stream/playlist.m3u8" },
{ name: "Canal+ Premium", url: "https://cdn-nvm-newyork.lolokoko.tv/CANALPLUSHD.stream/playlist.m3u8" },
{ name: "Cinemax", url: "https://cdn-nvm-newyork.lolokoko.tv/CINEMAXHD.stream/playlist.m3u8" },
{ name: "Cinemax 2", url: "https://cdn-nvm-newyork.lolokoko.tv/cinemaxcentraleurope2.stream/playlist.m3u8" },
{ name: "Red Carpet", url: "https://cdn-nvm-newyork.lolokoko.tv/REDCARPET.stream/playlist.m3u8" },
{ name: "AMC", url: "https://cdn-nvm-newyork.lolokoko.tv/AMC.stream/playlist.m3u8" },
{ name: "Novela TV", url: "https://cdn-nvm-newyork.lolokoko.tv/Novela.stream/playlist.m3u8" },
{ name: "Paramount Network", url: "https://cdn-nvm-newyork.lolokoko.tv/paramountchannel.stream/playlist.m3u8" },
{ name: "TLC", url: "https://cdn-nvm-newyork.lolokoko.tv/TLC.stream/playlist.m3u8" },
{ name: "Active Family", url: "https://cdn-nvm-newyork.lolokoko.tv/ACTIVEFAMILY.stream/playlist.m3u8" },
{ name: "Epic Drama", url: "https://cdn-nvm-newyork.lolokoko.tv/EPICDRAMA.stream/playlist.m3u8" },
{ name: "AXN "", url: "https://cdn-nvm-newyork.lolokoko.tv/AXNPolska.stream/playlist.m3u8" },
{ name: "AXN White", url: "https://cdn-nvm-newyork.lolokoko.tv/AXNWHITE.stream/playlist.m3u8" },
{ name: "AXN Black", url: "https://cdn-nvm-newyork.lolokoko.tv/AXNBLACK.stream/playlist.m3u8" },
{ name: "AXN Spin", url: "https://cdn-nvm-newyork.lolokoko.tv/AXNSPIN.stream/playlist.m3u8" },
{ name: "13 Ulica", url: "https://cdn-nvm-newyork.lolokoko.tv/13ULICA.stream/playlist.m3u8" },
{ name: "TV 6"", url: "https://cdn-nvm-newyork.lolokoko.tv/TV6.stream/playlist.m3u8" },
{ name: "MTV Polska", url: "https://cdn-nvm-newyork.lolokoko.tv/MTVPolska.stream/playlist.m3u8" },
{ name: "Kino Polska", url: "https://cdn-nvm-newyork.lolokoko.tv/KINOPOLSKA.stream/playlist.m3u8" },
{ name: "FilmBox Arthouse", url: "https://cdn-nvm-newyork.lolokoko.tv/FILMBOXARTHOUSE.stream/playlist.m3u8" },
{ name: "FilmBox Action", url: "https://cdn-nvm-newyork.lolokoko.tv/FILMBOXACTION.stream/playlist.m3u8" },
{ name: "FilmBox Premium"", url: "https://cdn-nvm-newyork.lolokoko.tv/FILMBOXPREMIUM.stream/playlist.m3u8" },
{ name: "FilmBox Extra", url: "https://cdn-nvm-newyork.lolokoko.tv/FILMBOXEXTRA.stream/playlist.m3u8" },
{ name: "FilmBox Family"", url: "https://cdn-nvm-newyork.lolokoko.tv/FILMBOXFAMILY.stream/playlist.m3u8" },
{ name: "CMC"", url: "https://cmc-ono.amagi.tv/hls/amagi_hls_data_cmcAAAAAA-cmc-ono/CDN/playlist.m3u8" },
{ name: "Polsat Rodzina", url: "https://cdn-nvm-newyork.lolokoko.tv/PolsatRodzina.stream/playlist.m3u8" },
{ name: "DTX"", url: "https://cdn-nvm-newyork.lolokoko.tv/DTX.stream/playlist.m3u8" },
{ name: "TTv", url: "https://cdn-nvm-newyork.lolokoko.tv/TTV.stream/playlist.m3u8" },
{ name: "TVN Fabu&#322;a", url: "https://cdn-nvm-newyork.lolokoko.tv/TVNFABULA.stream/playlist.m3u8" },
{ name: "TVN Style", url: "https://cdn-nvm-newyork.lolokoko.tv/TVNStyle.stream/playlist.m3u8" },
{ name: "Polonia 1"", url: "https://cdn-nvm-newyork.lolokoko.tv/POLONIA1.stream/playlist.m3u8" },
{ name: "Wydarzenia 24"", url: "https://cdn-nvm-newyork.lolokoko.tv/SUPERSTACJA.stream/playlist.m3u8" },
{ name: "TVP Historia", url: "https://cdn-nvm-newyork.lolokoko.tv/TVPHistoria.stream/playlist.m3u8" },
{ name: "TVP Kultura", url: "https://cdn-nvm-newyork.lolokoko.tv/TVPKultura.stream/playlist.m3u8" },
{ name: "TVP Seriale", url: "https://cdn-nvm-newyork.lolokoko.tv/TVPSeriale.stream/playlist.m3u8" },
{ name: "TVP Rozrywka", url: "https://cdn-nvm-newyork.lolokoko.tv/TVPRozrywka.stream/playlist.m3u8" },
{ name: "TVN 24"", url: "https://cdn-nvm-newyork.lolokoko.tv/TVN24.stream/playlist.m3u8" },
{ name: "TVN 24 BIs", url: "https://cdn-nvm-newyork.lolokoko.tv/TVN24BIS.stream/playlist.m3u8" },
{ name: "TVN Turbo"", url: "https://cdn-nvm-newyork.lolokoko.tv/TVNTURBO.stream/playlist.m3u8" },
{ name: "Motowizja", url: "https://cdn-nvm-newyork.lolokoko.tv/motowizja.stream/playlist.m3u8" },
{ name: "Warner Tv", url: "https://cdn-nvm-newyork.lolokoko.tv/TNT.stream/playlist.m3u8" },
{ name: "Kino Tv", url: "https://cdn-nvm-newyork.lolokoko.tv/FilmBox.stream/playlist.m3u8" },
{ name: "Polsat Film"", url: "https://cdn-nvm-newyork.lolokoko.tv/PolsatFilm.stream/playlist.m3u8" },
{ name: "Polsat News", url: "https://cdn-nvm-newyork.lolokoko.tv/PolsatNews.stream/playlist.m3u8" },
{ name: "Polsat News 2"", url: "https://cdn-nvm-newyork.lolokoko.tv/PolsatNews2.stream/playlist.m3u8" },
{ name: "TVP Sport"", url: "https://cdn-nvm-newyork.lolokoko.tv/TVPSport.stream/playlist.m3u8" },
{ name: "Polsat Sport"", url: "https://cdn-nvm-newyork.lolokoko.tv/PolsatSport.stream/playlist.m3u8" },
{ name: "Puls", url: "https://cdn-nvm-newyork.lolokoko.tv/TVPuls.stream/playlist.m3u8" },
{ name: "Puls 2"", url: "https://cdn-nvm-newyork.lolokoko.tv/TVPuls2.stream/playlist.m3u8" },
{ name: "Trwam"", url: "https://cdn-nvm-newyork.lolokoko.tv/TVTrwam.stream/playlist.m3u8" },
{ name: "Stopklatka", url: "https://cdn-nvm-newyork.lolokoko.tv/StopklatkaTV.stream/playlist.m3u8" },
{ name: "TVP 3"", url: "https://cdn-nvm-newyork.lolokoko.tv/TVP3Warszawa.stream/playlist.m3u8" },
{ name: "BBC First"", url: "https://cdn-nvm-newyork.lolokoko.tv/BBCHD.stream/playlist.m3u8" },
{ name: "BBC Earth"", url: "https://cdn-nvm-newyork.lolokoko.tv/bbcearth.stream/playlist.m3u8" },
{ name: "BBC Brit"", url: "https://cdn-nvm-newyork.lolokoko.tv/bbcbritpolska.stream/playlist.m3u8" },
{ name: "BBC LifeStyle", url: "https://cdn-nvm-newyork.lolokoko.tv/bbclifestyle.stream/playlist.m3u8" },
{ name: "Cartoon Network", url: "https://cdn-nvm-newyork.lolokoko.tv/cartonnetwork.stream/playlist.m3u8" },
{ name: "CBeebies", url: "https://cdn-nvm-newyork.lolokoko.tv/CBeebies.stream/playlist.m3u8" },
{ name: "TVP ABC"", url: "https://cdn-nvm-newyork.lolokoko.tv/TVPABC.stream/playlist.m3u8" },
{ name: "Mini Mini+"", url: "https://cdn-nvm-newyork.lolokoko.tv/MINIMINI.stream/playlist.m3u8" },
{ name: "Disney Junior"", url: "https://cdn-nvm-newyork.lolokoko.tv/DisneyJunior.stream/playlist.m3u8" },
{ name: "Disney XD"", url: "https://cdn-nvm-newyork.lolokoko.tv/DisneyXD.stream/playlist.m3u8" },
{ name: "Nickelodeon", url: "https://cdn-nvm-newyork.lolokoko.tv/Nickelodeon.stream/playlist.m3u8" },
{ name: "Nick Jr."", url: "https://cdn-nvm-newyork.lolokoko.tv/NickJr.stream/playlist.m3u8" },
{ name: "Nicktoons", url: "https://cdn-nvm-newyork.lolokoko.tv/Nicktoons.stream/playlist.m3u8" },
{ name: "Teletoon+"", url: "https://cdn-nvm-newyork.lolokoko.tv/Teletoon.stream/playlist.m3u8" },
{ name: "Nuta Tv", url: "https://cdn-nvm-newyork.lolokoko.tv/nuta.stream/playlist.m3u8" },
{ name: "Polo Tv", url: "https://cdn-nvm-newyork.lolokoko.tv/PoloTV.stream/playlist.m3u8" },
{ name: "Eska Tv", url: "https://cdn-nvm-newyork.lolokoko.tv/EskaTV.stream/playlist.m3u8" },
{ name: "Eska TV Extra", url: "https://cdn-nvm-newyork.lolokoko.tv/EskaTVExtra.stream/playlist.m3u8" },
{ name: "Eska TV Rock", url: "https://cdn-nvm-newyork.lolokoko.tv/powertv.stream/playlist.m3u8" },
{ name: "Stars Tv", url: "https://cdn-nvm-newyork.lolokoko.tv/STARSTV.stream/playlist.m3u8" },
{ name: "Bollywood"", url: "https://cdn-nvm-newyork.lolokoko.tv/Bollywood.stream/playlist.m3u8" },
{ name: "Zoom Tv", url: "https://cdn-nvm-newyork.lolokoko.tv/ZOOMTV.stream/playlist.m3u8" },
{ name: "TVs", url: "https://cdn-nvm-newyork.lolokoko.tv/TVS.stream/playlist.m3u8" },
{ name: "Canal+ Domo"", url: "https://cdn-nvm-newyork.lolokoko.tv/domo.stream/playlist.m3u8" },
{ name: "Canal+ Kuchnia", url: "https://cdn-nvm-newyork.lolokoko.tv/kuchniaplus.stream/playlist.m3u8" },
{ name: "HGTv", url: "https://cdn-nvm-newyork.lolokoko.tv/HGTV.stream/playlist.m3u8" },
{ name: "Home Tv", url: "https://cdn-nvm-newyork.lolokoko.tv/HOMETV.stream/playlist.m3u8" },
{ name: "History"", url: "https://cdn-nvm-newyork.lolokoko.tv/HISTORY.stream/playlist.m3u8" },
{ name: "History 2"", url: "https://cdn-nvm-newyork.lolokoko.tv/h2.stream/playlist.m3u8" },
{ name: "Animal Planet"", url: "https://cdn-nvm-newyork.lolokoko.tv/AnimalPlanet.stream/playlist.m3u8" },
{ name: "National Geographic"", url: "https://cdn-nvm-newyork.lolokoko.tv/nationalgeographic.stream/playlist.m3u8" },
{ name: "NatGeo People", url: "https://cdn-nvm-newyork.lolokoko.tv/natgeopeople.stream/playlist.m3u8" },
{ name: "NatGeo Wild"", url: "https://cdn-nvm-newyork.lolokoko.tv/natgeowild.stream/playlist.m3u8" },
{ name: "Planete+"", url: "https://cdn-nvm-newyork.lolokoko.tv/PlanetePlus.stream/playlist.m3u8" },
{ name: "FX Comedy"", url: "https://cdn-nvm-newyork.lolokoko.tv/FOXCOMEDY.stream/playlist.m3u8" },
{ name: "FX"", url: "https://cdn-nvm-newyork.lolokoko.tv/FOXPolska.stream/playlist.m3u8" },
{ name: "Comedy Central"", url: "https://cdn-nvm-newyork.lolokoko.tv/comedycentralpolska.stream/playlist.m3u8" },
{ name: "Canal+ Sport"", url: "https://cdn-nvm-newyork.lolokoko.tv/canalsport1_trans.stream/playlist.m3u8" },
{ name: "Canal+ Sport 2"", url: "https://cdn-nvm-newyork.lolokoko.tv/canalplussport2.stream/playlist.m3u8" },
{ name: "Canal+ Sport 3"", url: "https://cdn-nvm-newyork.lolokoko.tv/canalplussport3.stream/playlist.m3u8" },
{ name: "Canal+ Sport 4"", url: "https://cdn-nvm-newyork.lolokoko.tv/canalplussport4.stream/playlist.m3u8" },
{ name: "Canal+ Sport 5"", url: "https://cdn-nvm-newyork.lolokoko.tv/nsport_trans.stream/playlist.m3u8" },
{ name: "EuroSport 1"", url: "https://cdn-nvm-newyork.lolokoko.tv/eurosport1.stream/playlist.m3u8" },
{ name: "EuroSport 2"", url: "https://cdn-nvm-newyork.lolokoko.tv/eurosport2polska.stream/playlist.m3u8" },
{ name: "Extreme Sports", url: "https://cdn-nvm-newyork.lolokoko.tv/extremesportchanell.stream/playlist.m3u8" },
{ name: "Eleven Sports 1"", url: "https://cdn-nvm-newyork.lolokoko.tv/eleven1_trans.stream/playlist.m3u8" },
{ name: "Eleven Sports 2"", url: "https://cdn-nvm-newyork.lolokoko.tv/eleven2_trans.stream/playlist.m3u8" },
{ name: "Eleven Sports 3"", url: "https://cdn-nvm-newyork.lolokoko.tv/eleven3_trans.stream/playlist.m3u8" },
{ name: "Eleven Sports 4"", url: "https://cdn-nvm-newyork.lolokoko.tv/eleven4_trans.stream/playlist.m3u8" },
{ name: "Discovery Channel"", url: "https://cdn-nvm-newyork.lolokoko.tv/discoverychannel.stream/playlist.m3u8" },
{ name: "Discovery Historia", url: "https://cdn-nvm-newyork.lolokoko.tv/discoveryhistoria.stream/playlist.m3u8" },
{ name: "Discovery Life", url: "https://cdn-nvm-newyork.lolokoko.tv/discoverylife.stream/playlist.m3u8" },
{ name: "Discovery Science", url: "https://cdn-nvm-newyork.lolokoko.tv/discoveryogo.jpgsience.stream/playlist.m3u8" },
{ name: "Da Vinci"", url: "https://cdn-nvm-newyork.lolokoko.tv/davinci.stream/playlist.m3u8" },
{ name: "Food Network", url: "https://cdn-nvm-newyork.lolokoko.tv/foodnetwork.stream/playlist.m3u8" },
{ name: "Polsat Crime", url: "https://cdn-nvm-newyork.lolokoko.tv/polsatcrimeinvest.stream/playlist.m3u8" },
{ name: "Polsat Cafe", url: "https://cdn-nvm-newyork.lolokoko.tv/polsatcafe.stream/playlist.m3u8" },
{ name: "Polsat Comedy Extra", url: "https://cdn-nvm-newyork.lolokoko.tv/polsat_comedy_central.stream/playlist.m3u8" },
{ name: "Polsat Doku"", url: "https://cdn-nvm-newyork.lolokoko.tv/polsatdoku.stream/playlist.m3u8" },
{ name: "Polsat Games", url: "https://cdn-nvm-newyork.lolokoko.tv/polsatgames.stream/playlist.m3u8" },
{ name: "Polsat Music"", url: "https://cdn-nvm-newyork.lolokoko.tv/polsatmusic.stream/playlist.m3u8" },
{ name: "Polsat Play"", url: "https://cdn-nvm-newyork.lolokoko.tv/polsatplay.stream/playlist.m3u8" },
{ name: "Polsat Seriale", url: "https://cdn-nvm-newyork.lolokoko.tv/polsatromans.stream/playlist.m3u8" },
{ name: "Polsat Sport Extra", url: "https://cdn-nvm-newyork.lolokoko.tv/polsatsportextra.stream/playlist.m3u8" },
{ name: "Polsat Sport Fight"", url: "https://cdn-nvm-newyork.lolokoko.tv/sportfight_trans.stream/playlist.m3u8" },
{ name: "Polsat Sport News", url: "https://cdn-nvm-newyork.lolokoko.tv/polsatsportnews.stream/playlist.m3u8" },
{ name: "Polsat Sport Premium 1"", url: "https://cdn-nvm-newyork.lolokoko.tv/polsatsportp1.stream/playlist.m3u8" },
{ name: "Polsat Sport Premium 2"", url: "https://cdn-nvm-newyork.lolokoko.tv/polsatsportp2.stream/playlist.m3u8" },
{ name: "Polsat Viasat Explore", url: "https://cdn-nvm-newyork.lolokoko.tv/viasatexplore.stream/playlist.m3u8" },
{ name: "Polsat Viasat Nature", url: "https://cdn-nvm-newyork.lolokoko.tv/viasatnature.stream/playlist.m3u8" },
{ name: "Polsat Viasat History"", url: "https://cdn-nvm-newyork.lolokoko.tv/viasathistory.stream/playlist.m3u8" },
{ name: "FightBox"", url: "https://cdn-nvm-newyork.lolokoko.tv/fightbox.stream/playlist.m3u8" },
{ name: "Water Planet"", url: "https://cdn-nvm-newyork.lolokoko.tv/waterplanet.stream/playlist.m3u8" },
{ name: "Vox Music Tv", url: "https://cdn-nvm-newyork.lolokoko.tv/voxmusic.stream/playlist.m3u8" },
{ name: "Nick Music"", url: "https://cdn-nvm-newyork.lolokoko.tv/nickmusic.stream/playlist.m3u8" },
{ name: "Disco Polo Music"", url: "https://cdn-nvm-newyork.lolokoko.tv/discopolomusic.stream/playlist.m3u8" },
{ name: "CBS Reality"", url: "https://cdn-nvm-newyork.lolokoko.tv/cbsreality.stream/playlist.m3u8" },
{ name: "CBS Europa", url: "https://cdn-nvm-newyork.lolokoko.tv/cbseuropa.stream/playlist.m3u8" },
{ name: "4 Fun Dance", url: "https://cdn-nvm-newyork.lolokoko.tv/4fundance.stream/playlist.m3u8" },
{ name: "4 Fun Kids", url: "https://cdn-nvm-newyork.lolokoko.tv/4funhits2.stream/playlist.m3u8" },
{ name: "4 Fun Tv", url: "https://cdn-nvm-newyork.lolokoko.tv/4funtv.stream/playlist.m3u8" },
{ name: "TVT"", url: "https://live.streamtvt.pl/LiveAppStreamTVT/streams/853271271313930867905724.m3u8" },
{ name: "Truso Tv", url: "https://stream.truso.tv/elblag/myStream_aac/playlist.m3u8" },
{ name: "TV Jas&#322;o"", url: "https://cdn2.aztv.pl/hls/live_tvjaslo.stream.m3u8?conn_id=14013521122889531071"," },
{ name: "TV Regionalna", url: "https://tvreg.klemit.net/regionalna/stream/index.m3u8" },
{ name: "Pogranicze G&#322;ubczyce", url: "https://stream.elzappero.net/tvglubczyce.m3u8" },
{ name: "Telewizja Biznesowa", url: "https://s-pl-01.mediatool.tv/playout/tbpl-abr/index.m3u8" },
{ name: "TV Imperium "", url: "https://91-193-208-10.eimperium.pl/TVIMPERIUM/index.m3u8" },
{ name: "Radio Czw&#243;rka", url: "https://stream14.polskieradio.pl/pr4_video/video_pr4.stream/playlist.m3u8" },
{ name: "TVP Polonia", url: "https://cdn-nvm-newyork.lolokoko.tv/TVPPolonia.stream/playlist.m3u8" },
{ name: "TVP World"", url: "https://cdn-nvm-newyork.lolokoko.tv/TVPWorld.stream/playlist.m3u8" },
{ name: "TVP Nauka", url: "https://cdn-nvm-newyork.lolokoko.tv/TVPNauka.stream/playlist.m3u8" },
{ name: "Nuta Gold", url: "https://cdn-nvm-newyork.lolokoko.tv/GoldTV.stream/playlist.m3u8" },
{ name: "TVP Kobieta", url: "https://cdn-nvm-newyork.lolokoko.tv/tvp_kobieta.stream/playlist.m3u8" },
{ name: "Alfa TVP", url: "https://cdn-nvm-newyork.lolokoko.tv/tvp_alfa.stream/playlist.m3u8" },
{ name: "Travel Channel", url: "https://cdn-nvm-newyork.lolokoko.tv/travel.stream/playlist.m3u8" },
{ name: "TV Toru&#324; "", url: "https://mediaserwer.tvk.torun.pl/live/ngrp:tvk.stream_mobile/chunklist_w222650670_b3596000.m3u8" },
{ name: "TBN "", url: "https://cdn-nvm-newyork.lolokoko.tv/tbn.stream/playlist.m3u8" },
{ name: "E! Entertainment"", url: "https://cdn-nvm-newyork.lolokoko.tv/epolska.stream/playlist.m3u8" },
{ name: "Strefa Tv", url: "https://stream.sferatv.pl/sferatvlive/live.m3u8" },
{ name: "Fashion Tv", url: "https://cdn-nvm-newyork.lolokoko.tv/wcf.stream/playlist.m3u8" },
{ name: "dla Ciebie", url: "https://6034e09794f07.streamlock.net:443/tv/dlaCiebieTv/playlist.m3u8" }
    // Dodaj więcej kanałów według potrzeb
  ];

  function displayChannels(channels) {
    channelList.innerHTML = '';
    channels.forEach(channel => {
      const listItem = document.createElement('li');
      listItem.textContent = channel.name;
      listItem.addEventListener('click', function () {
        player.source = {
          type: 'video',
          sources: [
            {
              src: channel.url,
              type: 'application/x-mpegURL'
            }
          ]
        };
      });
      channelList.appendChild(listItem);
    });
  }

  searchInput.addEventListener('input', function () {
    const searchTerm = searchInput.value.toLowerCase();
    const filteredChannels = channels.filter(channel => 
      channel.name.toLowerCase().includes(searchTerm)
    );
    displayChannels(filteredChannels);
  });

  displayChannels(channels);
});
